# Generated by Django 5.1.6 on 2025-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hex_color',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
