# Generated by Django 5.1.6 on 2025-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('gopay', 'GoPay'), ('ovo', 'OVO'), ('shopeepay', 'ShopeePay')], max_length=20),
        ),
    ]
