# Generated by Django 5.1.7 on 2025-03-30 07:38

from django.db import connection, migrations

def fix_admin_log_fk(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;
        """)
        cursor.execute("""
            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES authentication_customuser(id) ON DELETE CASCADE;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.RunPython(fix_admin_log_fk),
    ]
