# Generated by Django 5.1.7 on 2025-04-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_managers'),
        ('authentication', '0007_alter_customuser_managers'),
    ]

    operations = [
    ]
