# Generated by Django 5.1.7 on 2025-04-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_20250414_0149'),
        ('authentication', '0008_merge_20250413_2112'),
    ]

    operations = [
    ]
